# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from servocontrol/state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class state(genpy.Message):
  _md5sum = "c95f0a0c1b57d8b8eaffcee8de0dcceb"
  _type = "servocontrol/state"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string last_cmd
uint8 step
float32 speed
uint8 x
uint8 y"""
  __slots__ = ['last_cmd','step','speed','x','y']
  _slot_types = ['string','uint8','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       last_cmd,step,speed,x,y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.last_cmd is None:
        self.last_cmd = ''
      if self.step is None:
        self.step = 0
      if self.speed is None:
        self.speed = 0.
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
    else:
      self.last_cmd = ''
      self.step = 0
      self.speed = 0.
      self.x = 0
      self.y = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.last_cmd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bf2B().pack(_x.step, _x.speed, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_cmd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_cmd = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.step, _x.speed, _x.x, _x.y,) = _get_struct_Bf2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.last_cmd
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bf2B().pack(_x.step, _x.speed, _x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_cmd = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_cmd = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.step, _x.speed, _x.x, _x.y,) = _get_struct_Bf2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bf2B = None
def _get_struct_Bf2B():
    global _struct_Bf2B
    if _struct_Bf2B is None:
        _struct_Bf2B = struct.Struct("<Bf2B")
    return _struct_Bf2B
